"""Add table project project_user and task

Revision ID: 3109964019ba
Revises: 1a31ce608336
Create Date: 2025-01-12 00:56:18.841595

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3109964019ba'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'project'
        ) THEN
            CREATE TABLE project (
                id UUID PRIMARY KEY,
                name VARCHAR NOT NULL,
                description VARCHAR NOT NULL,
                owner_id UUID NOT NULL
            );
        END IF;
    END $$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
