"""Add table project_user and task

Revision ID: 70e21a657190
Revises: 3109964019ba
Create Date: 2025-01-12 01:00:37.087497

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '70e21a657190'
down_revision = '3109964019ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'project_user'
        ) THEN
            CREATE TABLE project_user (
                project_id UUID NOT NULL,
                user_id UUID NOT NULL,
                role VARCHAR NOT NULL,
                CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES project (id),
                CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES "user" (id),
                CONSTRAINT pk_project_user PRIMARY KEY (project_id, user_id)
            );
        END IF;
    END $$;
    """)
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_name = 'task'
        ) THEN
            CREATE TABLE task (
                id UUID PRIMARY KEY,
                name VARCHAR NOT NULL,
                description VARCHAR NOT NULL,
                status VARCHAR NOT NULL,
                created_date TIMESTAMP NOT NULL,
                end_date TIMESTAMP NOT NULL,
                project_id UUID NOT NULL,
                assigner_id UUID,
                CONSTRAINT fk_project FOREIGN KEY (project_id) REFERENCES project (id),
                CONSTRAINT fk_assigner FOREIGN KEY (assigner_id) REFERENCES "user" (id)
            );
        END IF;
    END $$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('project_user')
    # ### end Alembic commands ###
