"""pull new task model

Revision ID: 9db8787d7e44
Revises: 4c3e690d7f96
Create Date: 2025-01-10 14:57:30.488880

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9db8787d7e44'
down_revision = '4c3e690d7f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
