"""fix delete

Revision ID: aeb882ea1562
Revises: 66d7115211b7
Create Date: 2025-01-13 02:06:05.362673

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aeb882ea1562'
down_revision = '66d7115211b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
