"""project_user remove

Revision ID: e4333f247bd4
Revises: a2c8faab1b67
Create Date: 2025-01-13 00:16:56.903270

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e4333f247bd4'
down_revision = 'a2c8faab1b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_user',
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='fk_project'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user'),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name='pk_project_user')
    )
    # ### end Alembic commands ###
